In [226]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data =pd.read_csv('dataset/purchase.csv')
data.head()

data.isna().sum()


Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [227]:
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Salary'].fillna(data['Salary'].mean(),inplace=True)

data

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [228]:
#extracting independent variables
x=data.iloc[:,:-1].values
#dependent variable
y=data.iloc[:,-1:].values



# x = pd.DataFrame(x)
# y=pd.DataFrame(y)



In [229]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)

y.reshape(-1,1)
print(y)

[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


In [230]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [231]:
from sklearn.preprocessing import StandardScaler
stX = StandardScaler()
xTrain = stX.fit_transform(xTrain)
xTest = stX.transform(xTest)

In [232]:
print(xTest)



[[-1.15470054  1.         -0.8660254  -1.33607682 -0.82778996]
 [-1.15470054  1.         -0.8660254   1.90134009  2.02036872]
 [-1.15470054  1.         -0.8660254   0.28263164  0.13250875]]
