In [2]:
import numpy as np

arr = np.uint16([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(5,2)
print('Dimensions of array: ', arr.ndim)
print('Shape of array: ', arr.shape)
print('Element size in bytes: ', arr.itemsize)







Dimensions of array:  2
Shape of array:  (5, 2)
Element size in bytes:  2


In [3]:
array = np.array([200,210,220,230,240,250,260,270,280,290] ,dtype=np.uint16)
array = array.reshape(5,2)
array

array([[200, 210],
       [220, 230],
       [240, 250],
       [260, 270],
       [280, 290]], dtype=uint16)

In [12]:
matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print('Third row of matrix: ', matrix[2,:])

Third row of matrix:  [[7 8 9]]


In [18]:
array1 = np.random.randint(1,10, size=(5,4))
print('Array1: \n', array1)
array2 = array1[::2,1::2]
array2

Array1: 
 [[1 4 6 8]
 [7 5 9 9]
 [9 1 3 1]
 [7 4 8 8]
 [9 3 7 6]]


array([[4, 8],
       [1, 1],
       [3, 6]])

In [23]:
arr = np.random.randint(1,10, size=(8,3))
print('Array: \n', arr)

print('Array after splitting: \n')
np.split(arr, 4)



Array: 
 [[6 7 6]
 [2 9 5]
 [6 8 3]
 [2 7 7]
 [9 3 5]
 [7 1 3]
 [9 6 6]
 [4 5 1]]
Array after splitting: 



[array([[6, 7, 6],
        [2, 9, 5]]),
 array([[6, 8, 3],
        [2, 7, 7]]),
 array([[9, 3, 5],
        [7, 1, 3]]),
 array([[9, 6, 6],
        [4, 5, 1]])]

In [40]:
arr = np.random.randint(10,30, size=(4,4))

arr1 = arr[:,arr[2,:].argsort()]
print('Array after sorting by row: ')
print(arr1,'\n')
print('Array after sorting by column: ')
arr1[:,arr1[1,:].argsort()]

Array after sorting by row: 
[[17 20 25 23]
 [14 18 12 16]
 [12 19 19 28]
 [15 24 20 26]] 

Array after sorting by column: 


array([[25, 17, 23, 20],
       [12, 14, 16, 18],
       [19, 12, 28, 19],
       [20, 15, 26, 24]])

In [46]:
array = np.array([1,2,3,4,5,6,7,8,9])
array = np.reshape(array, (3,3))

col = [10,11,12]
array[:,2] = col
array

array([[ 1,  2, 10],
       [ 4,  5, 11],
       [ 7,  8, 12]])